export type ProductImg = {
  fileName: string,
  label: string,
}

export const ProductsImgData: ProductImg[] = [
  { fileName: 'arbolitos-navidenos-1.jpg', label: 'arbolitos navideños' },
  { fileName: 'arreglo-floral-1-editado.jpg', label: 'arreglos florales' },
  { fileName: 'arreglo-floral-2-editado.jpg', label: 'arreglos florales' },
  { fileName: 'arreglo-floral-3.jpg', label: 'arreglos florales' },
  { fileName: 'arreglo-floral-4-editado.jpg', label: 'arreglos florales' },
  { fileName: 'arreglo-floral-5-editado.jpg', label: 'arreglos florales' },
  { fileName: 'arreglo-floral-6-editado.jpg', label: 'arreglos florales' },
  { fileName: 'arreglo-floral-7-editado.jpg', label: 'arreglos florales' },
  { fileName: 'arreglo-floral-9-editado.jpg', label: 'arreglos florales' },
  { fileName: 'arreglo-floral-10-editado.jpg', label: 'arreglos florales' },
  { fileName: 'arreglo-floral-13-editado.jpg', label: 'arreglos florales' },
  { fileName: 'arreglo-floral-14.jpg', label: 'arreglos florales' },
  { fileName: 'arreglo-floral-15-editado.jpg', label: 'arreglos florales' },
  { fileName: 'arreglo-floral-15-editado.jpg', label: 'arreglos florales' },
  { fileName: 'corona-navidena-1.jpg', label: 'coronas navideñas' },
  { fileName: 'corona-navidena-2.jpg', label: 'coronas navideñas' },
  { fileName: 'corona-navidena-3.jpg', label: 'coronas navideñas' },
  { fileName: 'cortina-1.jpg', label: 'cortinas' },
  { fileName: 'cortina-4-editado.jpg', label: 'cortinas' },
  { fileName: 'cortina-5.jpg', label: 'cortinas' },
  { fileName: 'cortina-6-editado.jpg', label: 'cortinas' },
  { fileName: 'cortina-7.jpg', label: 'cortinas' },
  { fileName: 'cortina-10.jpg', label: 'cortinas' },
  { fileName: 'cortina-11-editado.jpg', label: 'cortinas' },
  { fileName: 'cortina-12.jpg', label: 'cortinas' },
  { fileName: 'cortina-15-editado.jpg', label: 'cortinas' },
  { fileName: 'cortina-16.jpg', label: 'cortinas' },
  { fileName: 'cortina-17-editado.jpg', label: 'cortinas' },
  { fileName: 'lampara-1.jpg', label: 'lamparas' },
  { fileName: 'lampara-2.jpg', label: 'lamparas' },
  { fileName: 'lampara-4-editado.jpg', label: 'lamparas' },
  { fileName: 'lampara-12.jpg', label: 'lamparas' },
  { fileName: 'lampara-14.jpg', label: 'lamparas' },
  { fileName: 'lampara-15-editado.jpg', label: 'lamparas' },
  { fileName: 'lampara-19.jpg', label: 'lamparas' },
  { fileName: 'llaveros-1-editado.jpg', label: 'llaveros' },
  { fileName: 'panero-1-editado.jpg', label: 'paneros' },
  { fileName: 'panero-2-editado.jpg', label: 'paneros' },
  { fileName: 'panero-3-editado.jpg', label: 'paneros' },
  { fileName: 'panero-4-editado.jpg', label: 'paneros' },
  { fileName: 'panero-5-editado.jpg', label: 'paneros' },
  { fileName: 'panero-6.jpg', label: 'paneros' },
  { fileName: 'pantalla-esquinera-1-editado.jpg', label: 'pantallas esquineras' },
  { fileName: 'pantalla-esquinera-2-editado.jpg', label: 'pantallas esquineras' },
  { fileName: 'pantalla-esquinera-5-editado.jpg', label: 'pantallas esquineras' },
  { fileName: 'pantalla-techo-1.jpg', label: 'pantallas de techo' },
  { fileName: 'pantalla-techo-2.jpg', label: 'pantallas de techo' },
  { fileName: 'pantalla-techo-5-editado.jpg', label: 'pantallas de techo' },
  { fileName: 'portacubiertos-1-editado.jpg', label: 'portacubiertos' },
  { fileName: 'portacubiertos-2-editado.jpg', label: 'portacubiertos' },
  { fileName: 'portacubiertos-3-editado.jpg', label: 'portacubiertos' },
  { fileName: 'servilletero-1-editado.jpg', label: 'servilleteros' },
  { fileName: 'servilletero-1.jpg', label: 'servilleteros' },
  { fileName: 'servilletero-2.jpg', label: 'servilleteros' },
];
